config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :short_urls

  get "/urls/shared" => "short_urls#index", as: :shared_urls
  get "/urls" => "short_urls#index", as: :all_urls
  get "/:short_url" => "short_urls#open"

  match "/user/:id/url/:short_url" => "users#open", via: :get, as: :go_on_url
  get "/users" => "users#index"
  get "/user/:id" => "users#show", as: :user

  root "short_urls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/short_url_concern.rb
module ShortUrlConcern
	extend ActiveSupport::Concern
	include Rails.application.routes.url_helpers
	require 'net/http'

	def check_url
		uri = URI.parse(self.original_url.to_s)
		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = false

		@status = true
		# @code = nil
		# @error = nil

		request = Net::HTTP::Get.new(uri.request_uri)

		begin
			#puts "============================================================================= ONE"
			#puts "code \"#{@code}\", status \"#{@status}\""
			#puts "URI \"#{uri.request_uri}\""

			res = http.request(request) rescue false

			@code = res.code.to_i

		rescue Errno::ECONNRESET => error_message
			@error = error_message

			errors.add(:original_url, "This doesn't appear to be an valid site. #{@error.message}")
			return
		end
	end
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  include ShortUrlsHelper

  belongs_to :user
  before_save :generate_short_url

  scope :shared, -> { where(shared: true) }

  validates :original_url, url: true

  validates :user_id, presence: true
  validates :short_url, uniqueness: true, presence: false
  validates :original_url, uniqueness: true, presence: true
  validates_length_of :short_url, maximum: 12

  def original
    original_url
  end

  def short
    short_url
  end

  private

  def generate_short_url
    chars = ['0'..'9', 'A'..'Z', 'a'..'z'].map { |range| range.to_a }.flatten
    if self.short_url.blank?
      self.short_url = Random.new.rand(6..12).times.map { chars.sample }.join
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :short_urls, dependent: :destroy
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/job_managers_concern.rb
module AddonsForJobManagers
  # extend ActiveSupport::Concern

=begin
  included do
    #attr_reader :month, :contests
    #before_filter :build_month_lists
    #before_filter :set_current_month
    #before_filter :load_contests_for_current_month
  end

  def job_start
    unless JobManager.job_running?
      ShortUrlJob.set(wait: 1.minute).perform_later
      update_status("working")
    end
  end

  def job_stop
    if JobManager.job_running?
      update_status("stopped")
    end
  end

  def update_status(status)
    update(status: status)
  end
=end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def Index
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: [:show, :edit, :update, :destroy]

  def index
    # @short_urls = ShortUrl.where(shared: true)
    @short_urls = ShortUrl.shared
    #@short_urls = request.path_info.include?('shared') ? ShortUrl.where(shared: true) : ShortUrl.all
  end

  def show
  end

  def open
    if @short_url = ShortUrl.find_by(short_url: params[:short_url])
      redirect_to @short_url.original_url
    else
      redirect_to shared_urls_path
    end
  end

  def new
    @short_url = ShortUrl.new
  end

  def create
    @short_url = ShortUrl.new(url_params)

    respond_to do |format|
      if @short_url.save

        run_clean_job unless @short_url.permanent

        format.html { redirect_to user_path(current_user), notice: 'Short url was successfully created.' }
        format.json { render :show, status: :created, location: cerrent_user }
      else
        format.html { render :new }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @short_url.update(url_params)
        format.html { redirect_to user_path(current_user), notice: 'Short url was successfully updated.' }
        format.json { render :show, status: :ok, location: cerrent_user }
      else
        format.html { render :edit }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @short_url.destroy
    respond_to do |format|
      format.html { redirect_to shared_urls_path, notice: 'Short url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def url_params
    params.require(:short_url).permit(:user_id, :shared, :permanent, :original_url)
  end

  def set_short_url
    @short_url = ShortUrl.find(params[:id])
  end

  def run_clean_job
    ShortUrlJob.set(wait: 1.minute).perform_later
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def show
    #@shared_urls = @user.short_urls.where(shared: true).and('created_at <= ?', 1.minute.ago)
    @shared_urls = @user.short_urls.where(shared: true)
    @private_urls = @user.short_urls.where(shared: false)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def open
    @url = ShortUrl.where(short_url: params[:short_url]).first
    redirect_to @url.original
    return
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new user_params

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:index)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #def is_url_owner?(user_signed_in, current_user)
  def is_url_owner?(short_url)
    user_signed_in? and short_url.user_id == current_user.id
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/job_managers_helper.rb
module JobManagersHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_pages/Index.slim
h1 Index
p = link_to "Short URLs", short_urls_path

app/views/layouts/_navbar.slim
nav class="navbar navbar-expand-lg navbar-light bg-light"
  div class="container-fluid"
    ul class="nav nav-pills"
      // li class="nav-item"= link_to "USERS", users_path, class: "nav-link"
      li class="nav-item"= link_to "SHARED URLS", shared_urls_path, class: "nav-link"
      // li class="nav-item"= link_to "ALL URLS", all_urls_path, class: "nav-link"
    div class="form-inline" id="navbarNavDropdown"
      ul class="navbar-nav mr-auto"
        - unless user_signed_in?
          li class="nav-item dropdown"
            a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              |SIGN UP or SIGN IN
            div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"
              = link_to "SIGN UP", new_user_registration_path, class: "dropdown-item"
              = link_to "SIGN IN", new_user_session_path, class: "dropdown-item"
        - if user_signed_in?
          li class="nav-item dropdown"
            a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              = current_user.email
            div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"
              = link_to "profile", current_user, class: "dropdown-item"
              = link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrlApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container-fluid"><%= yield %></div>

  </body>
</html>

app/views/short_urls/_for_signed_users.slim
// - if short_url.is_url_owner?(user_signed_in?, current_user)
- if is_url_owner?(short_url)
	td= link_to 'Edit', edit_short_url_path(short_url)
	td= link_to 'Destroy', short_url, method: :delete, data: {confirm: 'Are you sure?'}


/- if user_signed_in?
	= render "short_urls/list"
/- else
	div class="jumbotron center-block"
		div style="margin-left: auto; margin-right: auto; width: 200px; test-align: center"
			div class="nav-item"= link_to "SIGN IN", new_user_session_path, class: "btn btn-primary btn-lg", role: "button"
			div class="nav-item justify-content-center" style="justify-content: space-around; test-align: center" OR
			div class="nav-item"= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg", role: "button"

app/views/short_urls/_form.slim
= form_with(model: short_url, local: true) do |form|
  - if short_url.errors.any?
    div id="error_explanation"
      h4
        = pluralize(short_url.errors.count, "error")
        |prohibited this short_url from being saved:
      - short_url.errors.full_messages.each do |message|
        div class="alert alert-danger"= message

  = form.hidden_field :user_id, value: current_user.id if user_signed_in?

  div class="form-group"
    = form.label :original_url
    = form.text_area :original_url, id: :short_url_original_url, class: "form-control"

  //div class="form-group"
    = form.label :short_url
    = form.text_field :short_url, id: :short_url_short_url, class: "form-control"

  div class="form-group"
    div class="form-check"
      label class="form-check-label"
      = form.check_box :shared, class: "form-check-input"
      |  Shared

  div class="form-group"
    div class="form-check"
      label class="form-check-label"
      = form.check_box :permanent, class: "form-check-input"
      |  Permanent

  div class="form-group"
    = form.submit class: "btn btn-primary"

app/views/short_urls/_list.slim
p id="notice"= notice

h3 Short Urls

table class="table table-striped"
  thead
    tr
      th User
      th Original url
      th Short url
      th Shared
      th Permanent
      - if user_signed_in?
        th colspan="3" actions

  tbody
    - @short_urls.each do |short_url|
      tr
        td= short_url.user_id
        td
          span title="#{short_url.original_url}"
            = short_url.original_url.truncate(27)
        td= link_to "https://vstestsurl.herokuapp.com/#{short_url.short_url}", "https://vstestsurl.herokuapp.com/#{short_url.short_url}"
        td= short_url.shared ? "true" : "false"
        td= short_url.permanent ? "true" : "false"
        = render "short_urls/for_signed_users", short_url: short_url

br

- if user_signed_in?
	= link_to 'New Short Url', new_short_url_path
- else
	= link_to "SIGN IN", new_user_session_path, class: "btn btn-primary btn-sm", role: "button"

app/views/short_urls/edit.html.erb
<h1>Editing Short Url</h1>

<%= render 'form', short_url: @short_url %>

<%= link_to 'Show', @short_url %> |
<%= link_to 'Back', short_urls_path %>

app/views/short_urls/index.slim
= render "short_urls/list"

app/views/short_urls/new.slim
h4 New Short Url

= render 'form', short_url: @short_url

= link_to 'Back', short_urls_path

app/views/short_urls/show.slim
p id="notice"= notice

p
  strong User:
  = @short_url.user_id

p
  strong Original url:
  = @short_url.original_url

p
  strong Short url:
  = @short_url.short_url

// - if @short_url.is_url_owner?(user_signed_in?, current_user)
- if is_url_owner?(@short_url)
  = link_to 'Edit', edit_short_url_path(@short_url)
  ' |
  = link_to 'Back', short_urls_path

app/views/users/index.slim
p id="notice"= notice

h3 Users

table class="table table-striped"
	thead
		tr
			th colspan="0" mail

	tbody
		- @users.each do |user|
			tr
				td= link_to user.id, user
/td= link_to 'Edit', edit_devise_user_path(user)
/td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/show.slim
h3
  |User
  '
  = @user.id

.container
  - if @private_urls && (current_user == @user)
    h5 PRIVATE URLS

    table class="table table-striped"
      thead
        tr
          th original url
          th short url
          th permanent
          th colspan="3" actions

      tbody
        - @private_urls.each do |url|
          tr
            td
              span title="#{url.original_url}"
                = url.original_url.truncate(27)
            td= link_to "https://sim-url.herokuapp.com/#{url.short_url}", "https://sim-url.herokuapp.com/#{url.short_url}"
            td= url.permanent ? "true" : "false"
            = render "short_urls/for_signed_users", short_url: url

.container style="margin-top: 60px"
  - if @shared_urls
    h5 SHARED URLS

    table class="table table-striped"
      thead
        tr
          th original url
          th short url
          th permanent
          th colspan="3" actions

      tbody
        - @shared_urls.each do |url|
          tr
            td
              span title="#{url.original_url}"
                = url.original_url.truncate(27)
            td= link_to "https://sim-url.herokuapp.com/#{url.short_url}", "https://sim-url.herokuapp.com/#{url.short_url}"
            td= url.permanent ? "true" : "false"
            = render "short_urls/for_signed_users", short_url: url

= link_to "Add URL", new_short_url_path